"""SRD 5.1 spell class availability generated from dnd5eapi.co.

The data is checked into the repository so runtime code does not call
external services. Values are lowercase D&D class keys.
"""

SPELL_CLASSES_BY_KEY = {
    'acid_arrow': ['wizard'],
    'acid_splash': ['sorcerer', 'wizard'],
    'aid': ['cleric', 'paladin'],
    'alarm': ['ranger', 'wizard'],
    'alter_self': ['sorcerer', 'wizard'],
    'animal_friendship': ['bard', 'druid', 'ranger'],
    'animal_messenger': ['bard', 'druid', 'ranger'],
    'animal_shapes': ['druid'],
    'animate_dead': ['cleric', 'wizard'],
    'animate_objects': ['bard', 'sorcerer', 'wizard'],
    'antilife_shell': ['druid'],
    'antimagic_field': ['cleric', 'wizard'],
    'antipathy_sympathy': ['druid', 'wizard'],
    'arcane_eye': ['cleric', 'wizard'],
    'arcane_hand': ['wizard'],
    'arcane_lock': ['wizard'],
    'arcane_sword': ['bard', 'wizard'],
    'arcanist_s_magic_aura': ['wizard'],
    'arms_of_hadar': ['warlock'],
    'astral_projection': ['cleric', 'warlock', 'wizard'],
    'augury': ['cleric'],
    'awaken': ['bard', 'druid'],
    'bane': ['bard', 'cleric'],
    'banishing_smite': ['paladin'],
    'banishment': ['cleric', 'paladin', 'sorcerer', 'warlock', 'wizard'],
    'barkskin': ['druid', 'ranger'],
    'beacon_of_hope': ['cleric'],
    'beast_sense': ['druid', 'ranger'],
    'bestow_curse': ['bard', 'cleric', 'wizard'],
    'black_tentacles': ['wizard'],
    'blade_barrier': ['cleric'],
    'blade_ward': ['bard', 'sorcerer', 'warlock', 'wizard'],
    'bless': ['cleric', 'paladin'],
    'blight': ['druid', 'sorcerer', 'warlock', 'wizard'],
    'blindness_deafness': ['bard', 'cleric', 'sorcerer', 'wizard'],
    'blink': ['sorcerer', 'wizard'],
    'blur': ['sorcerer', 'wizard'],
    'branding_smite': ['paladin'],
    'burning_hands': ['sorcerer', 'wizard'],
    'call_lightning': ['druid'],
    'calm_emotions': ['bard', 'cleric'],
    'chain_lightning': ['sorcerer', 'wizard'],
    'charm_person': ['bard', 'druid', 'sorcerer', 'warlock', 'wizard'],
    'chill_touch': ['sorcerer', 'warlock', 'wizard'],
    'circle_of_death': ['sorcerer', 'warlock', 'wizard'],
    'circle_of_power': ['paladin'],
    'clairvoyance': ['bard', 'cleric', 'sorcerer', 'wizard'],
    'clone': ['wizard'],
    'cloudkill': ['sorcerer', 'wizard'],
    'color_spray': ['sorcerer', 'wizard'],
    'command': ['cleric', 'paladin'],
    'commune': ['cleric'],
    'commune_with_nature': ['druid', 'ranger'],
    'compelled_duel': ['paladin'],
    'comprehend_languages': ['bard', 'sorcerer', 'warlock', 'wizard'],
    'compulsion': ['bard'],
    'cone_of_cold': ['sorcerer', 'wizard'],
    'confusion': ['bard', 'druid', 'sorcerer', 'wizard'],
    'conjure_animals': ['druid', 'ranger'],
    'conjure_barrage': ['ranger'],
    'conjure_celestial': ['cleric'],
    'conjure_elemental': ['druid', 'wizard'],
    'conjure_fey': ['druid', 'warlock'],
    'conjure_minor_elementals': ['druid', 'wizard'],
    'conjure_woodland_beings': ['druid', 'ranger'],
    'contact_other_plane': ['warlock', 'wizard'],
    'contagion': ['cleric', 'druid'],
    'contingency': ['wizard'],
    'continual_flame': ['cleric', 'wizard'],
    'control_water': ['cleric', 'druid', 'wizard'],
    'control_weather': ['cleric', 'druid', 'wizard'],
    'counterspell': ['sorcerer', 'warlock', 'wizard'],
    'create_bonfire': ['druid', 'sorcerer', 'warlock', 'wizard'],
    'create_food_and_water': ['cleric', 'druid', 'paladin'],
    'create_or_destroy_water': ['cleric', 'druid'],
    'create_undead': ['cleric', 'warlock', 'wizard'],
    'creation': ['sorcerer', 'wizard'],
    'cure_wounds': ['bard', 'cleric', 'druid', 'paladin', 'ranger'],
    'dancing_lights': ['bard', 'sorcerer', 'wizard'],
    'darkness': ['sorcerer', 'warlock', 'wizard'],
    'darkvision': ['druid', 'ranger', 'sorcerer', 'wizard'],
    'daylight': ['cleric', 'druid', 'paladin', 'ranger', 'sorcerer'],
    'death_ward': ['cleric', 'paladin'],
    'delayed_blast_fireball': ['sorcerer', 'wizard'],
    'demiplane': ['warlock', 'wizard'],
    'destructive_wave': ['paladin'],
    'detect_evil_and_good': ['cleric', 'paladin'],
    'detect_magic': ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'sorcerer', 'wizard'],
    'detect_poison_and_disease': ['cleric', 'druid', 'paladin', 'ranger'],
    'detect_thoughts': ['bard', 'sorcerer', 'wizard'],
    'dimension_door': ['bard', 'sorcerer', 'warlock', 'wizard'],
    'disguise_self': ['bard', 'sorcerer', 'wizard'],
    'disintegrate': ['sorcerer', 'wizard'],
    'dispel_evil_and_good': ['cleric', 'paladin'],
    'dispel_magic': ['bard', 'cleric', 'druid', 'paladin', 'sorcerer', 'warlock', 'wizard'],
    'divination': ['druid'],
    'divine_favor': ['paladin'],
    'divine_word': ['cleric'],
    'dominate_beast': ['druid', 'sorcerer'],
    'dominate_monster': ['bard', 'sorcerer', 'warlock', 'wizard'],
    'dominate_person': ['bard', 'sorcerer', 'wizard'],
    'dream': ['bard', 'warlock', 'wizard'],
    'druidcraft': ['druid'],
    'earthquake': ['cleric', 'druid', 'sorcerer'],
    'eldritch_blast': ['warlock'],
    'enhance_ability': ['bard', 'cleric', 'druid', 'sorcerer'],
    'enlarge_reduce': ['sorcerer', 'wizard'],
    'ensnaring_strike': ['ranger'],
    'entangle': ['druid'],
    'enthrall': ['bard', 'warlock'],
    'etherealness': ['bard', 'cleric', 'sorcerer', 'warlock', 'wizard'],
    'expeditious_retreat': ['sorcerer', 'warlock', 'wizard'],
    'eyebite': ['bard', 'sorcerer', 'warlock', 'wizard'],
    'fabricate': ['wizard'],
    'faerie_fire': ['druid'],
    'faithful_hound': ['wizard'],
    'false_life': ['sorcerer', 'wizard'],
    'fear': ['bard', 'sorcerer', 'warlock', 'wizard'],
    'feather_fall': ['bard', 'sorcerer', 'wizard'],
    'feeblemind': ['bard', 'druid', 'warlock', 'wizard'],
    'feign_death': ['bard', 'cleric', 'druid', 'wizard'],
    'find_familiar': ['wizard'],
    'find_steed': ['paladin'],
    'find_the_path': ['bard', 'cleric', 'druid'],
    'find_traps': ['cleric', 'druid', 'ranger'],
    'finger_of_death': ['sorcerer', 'warlock', 'wizard'],
    'fire_bolt': ['sorcerer', 'wizard'],
    'fire_shield': ['wizard'],
    'fire_storm': ['cleric', 'druid', 'sorcerer'],
    'fireball': ['sorcerer', 'wizard'],
    'flame_blade': ['druid'],
    'flame_strike': ['cleric'],
    'flaming_sphere': ['druid', 'wizard'],
    'flesh_to_stone': ['warlock', 'wizard'],
    'floating_disk': ['wizard'],
    'fly': ['sorcerer', 'warlock', 'wizard'],
    'fog_cloud': ['druid', 'ranger', 'sorcerer', 'wizard'],
    'forbiddance': ['cleric'],
    'forcecage': ['bard', 'warlock', 'wizard'],
    'foresight': ['bard', 'druid', 'warlock', 'wizard'],
    'freedom_of_movement': ['bard', 'cleric', 'druid', 'ranger'],
    'freezing_sphere': ['wizard'],
    'frostbite': ['druid', 'sorcerer', 'warlock', 'wizard'],
    'gaseous_form': ['sorcerer', 'warlock', 'wizard'],
    'gate': ['cleric', 'sorcerer', 'wizard'],
    'geas': ['bard', 'cleric', 'druid', 'paladin', 'wizard'],
    'gentle_repose': ['cleric', 'wizard'],
    'giant_insect': ['druid'],
    'glibness': ['bard', 'warlock'],
    'globe_of_invulnerability': ['sorcerer', 'wizard'],
    'glyph_of_warding': ['bard', 'cleric', 'wizard'],
    'goodberry': ['druid', 'ranger'],
    'grease': ['wizard'],
    'greater_invisibility': ['bard', 'sorcerer', 'wizard'],
    'greater_restoration': ['bard', 'cleric', 'druid'],
    'guardian_of_faith': ['cleric'],
    'guards_and_wards': ['bard', 'wizard'],
    'guidance': ['cleric', 'druid'],
    'guiding_bolt': ['cleric'],
    'gust_of_wind': ['druid', 'sorcerer', 'wizard'],
    'hallow': ['cleric'],
    'hallucinatory_terrain': ['bard', 'druid', 'warlock', 'wizard'],
    'harm': ['cleric'],
    'haste': ['sorcerer', 'wizard'],
    'heal': ['cleric', 'druid'],
    'healing_word': ['bard', 'cleric', 'druid'],
    'heat_metal': ['bard', 'druid'],
    'hellish_rebuke': ['warlock'],
    'heroes_feast': ['cleric', 'druid'],
    'heroism': ['bard', 'paladin'],
    'hideous_laughter': ['bard', 'wizard'],
    'hold_monster': ['bard', 'sorcerer', 'warlock', 'wizard'],
    'hold_person': ['bard', 'cleric', 'druid', 'sorcerer', 'warlock', 'wizard'],
    'holy_aura': ['cleric'],
    'hunter_s_mark': ['ranger'],
    'hypnotic_pattern': ['bard', 'sorcerer', 'warlock', 'wizard'],
    'ice_storm': ['druid', 'sorcerer', 'wizard'],
    'identify': ['bard', 'wizard'],
    'illusory_script': ['bard', 'warlock', 'wizard'],
    'imprisonment': ['warlock', 'wizard'],
    'incendiary_cloud': ['sorcerer', 'wizard'],
    'inflict_wounds': ['cleric'],
    'insect_plague': ['cleric', 'druid', 'sorcerer'],
    'instant_summons': ['wizard'],
    'invisibility': ['bard', 'sorcerer', 'warlock', 'wizard'],
    'irresistible_dance': ['bard', 'wizard'],
    'jump': ['druid', 'ranger', 'sorcerer', 'wizard'],
    'knock': ['bard', 'sorcerer', 'wizard'],
    'legend_lore': ['bard', 'cleric', 'wizard'],
    'lesser_restoration': ['bard', 'cleric', 'druid', 'paladin', 'ranger'],
    'levitate': ['sorcerer', 'wizard'],
    'light': ['bard', 'cleric', 'sorcerer', 'wizard'],
    'lightning_arrow': ['ranger'],
    'lightning_bolt': ['sorcerer', 'wizard'],
    'locate_animals_or_plants': ['bard', 'druid', 'ranger'],
    'locate_creature': ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'wizard'],
    'locate_object': ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'wizard'],
    'longstrider': ['bard', 'druid', 'ranger', 'wizard'],
    'mage_armor': ['sorcerer', 'wizard'],
    'mage_hand': ['bard', 'sorcerer', 'warlock', 'wizard'],
    'magic_circle': ['cleric', 'paladin', 'warlock', 'wizard'],
    'magic_jar': ['wizard'],
    'magic_missile': ['sorcerer', 'wizard'],
    'magic_mouth': ['bard', 'wizard'],
    'magic_weapon': ['paladin', 'wizard'],
    'magnificent_mansion': ['bard', 'wizard'],
    'major_image': ['bard', 'sorcerer', 'warlock', 'wizard'],
    'mass_cure_wounds': ['bard', 'cleric', 'druid'],
    'mass_heal': ['cleric'],
    'mass_healing_word': ['cleric'],
    'mass_suggestion': ['bard', 'sorcerer', 'warlock', 'wizard'],
    'maze': ['wizard'],
    'meld_into_stone': ['cleric'],
    'mending': ['bard', 'cleric', 'druid', 'sorcerer', 'wizard'],
    'message': ['bard', 'sorcerer', 'wizard'],
    'meteor_swarm': ['sorcerer', 'wizard'],
    'mind_blank': ['bard', 'wizard'],
    'minor_illusion': ['bard', 'sorcerer', 'warlock', 'wizard'],
    'mirage_arcane': ['bard', 'druid', 'wizard'],
    'mirror_image': ['sorcerer', 'warlock', 'wizard'],
    'mislead': ['bard', 'wizard'],
    'misty_step': ['sorcerer', 'warlock', 'wizard'],
    'modify_memory': ['bard', 'wizard'],
    'moonbeam': ['druid'],
    'move_earth': ['druid', 'sorcerer', 'wizard'],
    'nondetection': ['bard', 'ranger', 'wizard'],
    'pass_without_trace': ['druid', 'ranger'],
    'passwall': ['wizard'],
    'phantasmal_force': ['bard', 'sorcerer', 'wizard'],
    'phantasmal_killer': ['wizard'],
    'phantom_steed': ['wizard'],
    'planar_ally': ['cleric'],
    'planar_binding': ['bard', 'cleric', 'druid', 'wizard'],
    'plane_shift': ['cleric', 'druid', 'sorcerer', 'warlock', 'wizard'],
    'plant_growth': ['bard', 'druid', 'ranger'],
    'poison_spray': ['druid', 'sorcerer', 'warlock', 'wizard'],
    'polymorph': ['bard', 'druid', 'sorcerer', 'wizard'],
    'power_word_kill': ['bard', 'sorcerer', 'warlock', 'wizard'],
    'power_word_stun': ['bard', 'sorcerer', 'warlock', 'wizard'],
    'prayer_of_healing': ['cleric'],
    'prestidigitation': ['bard', 'sorcerer', 'warlock', 'wizard'],
    'prismatic_spray': ['sorcerer', 'wizard'],
    'prismatic_wall': ['wizard'],
    'private_sanctum': ['wizard'],
    'produce_flame': ['druid'],
    'programmed_illusion': ['bard', 'wizard'],
    'project_image': ['bard', 'wizard'],
    'protection_from_energy': ['cleric', 'druid', 'ranger', 'sorcerer', 'wizard'],
    'protection_from_evil_and_good': ['cleric', 'paladin', 'warlock', 'wizard'],
    'protection_from_poison': ['cleric', 'druid', 'paladin', 'ranger'],
    'purify_food_and_drink': ['cleric', 'druid', 'paladin'],
    'raise_dead': ['bard', 'cleric', 'paladin'],
    'ray_of_enfeeblement': ['warlock', 'wizard'],
    'ray_of_frost': ['sorcerer', 'wizard'],
    'regenerate': ['bard', 'cleric', 'druid'],
    'reincarnate': ['druid'],
    'remove_curse': ['cleric', 'paladin', 'warlock', 'wizard'],
    'resilient_sphere': ['wizard'],
    'resistance': ['cleric', 'druid'],
    'resurrection': ['bard', 'cleric'],
    'reverse_gravity': ['druid', 'sorcerer', 'wizard'],
    'revivify': ['cleric', 'paladin'],
    'rope_trick': ['wizard'],
    'sacred_flame': ['cleric'],
    'sanctuary': ['cleric'],
    'scorching_ray': ['sorcerer', 'wizard'],
    'scrying': ['bard', 'cleric', 'druid', 'warlock', 'wizard'],
    'searing_smite': ['paladin'],
    'secret_chest': ['wizard'],
    'see_invisibility': ['bard', 'sorcerer', 'wizard'],
    'seeming': ['bard', 'sorcerer', 'wizard'],
    'sending': ['bard', 'cleric', 'wizard'],
    'sequester': ['wizard'],
    'shapechange': ['druid', 'wizard'],
    'shatter': ['bard', 'sorcerer', 'warlock', 'wizard'],
    'shield': ['sorcerer', 'wizard'],
    'shield_of_faith': ['cleric', 'paladin'],
    'shillelagh': ['druid'],
    'shocking_grasp': ['sorcerer', 'wizard'],
    'silence': ['bard', 'cleric', 'ranger'],
    'silent_image': ['bard', 'sorcerer', 'wizard'],
    'simulacrum': ['wizard'],
    'sleep': ['bard', 'sorcerer', 'wizard'],
    'sleet_storm': ['druid', 'sorcerer', 'wizard'],
    'slow': ['sorcerer', 'wizard'],
    'spare_the_dying': ['cleric'],
    'speak_with_animals': ['bard', 'druid', 'ranger'],
    'speak_with_dead': ['bard', 'cleric'],
    'speak_with_plants': ['bard', 'druid', 'ranger'],
    'spider_climb': ['sorcerer', 'warlock', 'wizard'],
    'spike_growth': ['druid', 'ranger'],
    'spirit_guardians': ['cleric'],
    'spiritual_weapon': ['cleric'],
    'stinking_cloud': ['bard', 'sorcerer', 'wizard'],
    'stone_shape': ['cleric', 'druid', 'wizard'],
    'stoneskin': ['druid', 'ranger', 'sorcerer', 'wizard'],
    'storm_of_vengeance': ['druid'],
    'suggestion': ['bard', 'sorcerer', 'warlock', 'wizard'],
    'sunbeam': ['druid', 'sorcerer', 'wizard'],
    'sunburst': ['druid', 'sorcerer', 'wizard'],
    'symbol': ['bard', 'cleric', 'wizard'],
    'telekinesis': ['sorcerer', 'wizard'],
    'telepathic_bond': ['wizard'],
    'teleport': ['bard', 'sorcerer', 'wizard'],
    'teleportation_circle': ['bard', 'sorcerer', 'wizard'],
    'thaumaturgy': ['cleric'],
    'thunderous_smite': ['paladin'],
    'thunderwave': ['bard', 'druid', 'sorcerer', 'wizard'],
    'time_stop': ['sorcerer', 'wizard'],
    'tiny_hut': ['bard', 'wizard'],
    'toll_the_dead': ['cleric', 'warlock', 'wizard'],
    'tongues': ['bard', 'cleric', 'sorcerer', 'warlock', 'wizard'],
    'transport_via_plants': ['druid'],
    'tree_stride': ['druid', 'ranger'],
    'true_polymorph': ['bard', 'warlock', 'wizard'],
    'true_resurrection': ['cleric', 'druid'],
    'true_seeing': ['bard', 'cleric', 'sorcerer', 'warlock', 'wizard'],
    'true_strike': ['bard', 'sorcerer', 'warlock', 'wizard'],
    'tsunami': ['druid'],
    'unseen_servant': ['bard', 'warlock', 'wizard'],
    'vampiric_touch': ['warlock', 'wizard'],
    'vicious_mockery': ['bard'],
    'wall_of_fire': ['druid', 'sorcerer', 'wizard'],
    'wall_of_force': ['wizard'],
    'wall_of_ice': ['wizard'],
    'wall_of_stone': ['druid', 'sorcerer', 'wizard'],
    'wall_of_thorns': ['druid'],
    'warding_bond': ['cleric'],
    'water_breathing': ['druid', 'ranger', 'sorcerer', 'wizard'],
    'water_walk': ['cleric', 'druid', 'ranger', 'sorcerer'],
    'web': ['sorcerer', 'wizard'],
    'weird': ['wizard'],
    'wind_walk': ['druid'],
    'wind_wall': ['druid', 'ranger'],
    'wish': ['sorcerer', 'wizard'],
    'word_of_radiance': ['cleric'],
    'word_of_recall': ['cleric'],
    'wrathful_smite': ['paladin'],
    'zone_of_truth': ['bard', 'cleric', 'paladin'],
}
