"""SRD 5.1 CC-BY-4.0 item name manifest for seed audit.

Reconcile against official SRD 5.1 Creative Commons source.
"""

SRD_ITEMS_BY_CATEGORY = {
    "simple_weapon": [
        "Club",
        "Dagger",
        "Greatclub",
        "Handaxe",
        "Javelin",
        "Light Hammer",
        "Mace",
        "Quarterstaff",
        "Sickle",
        "Spear",
        "Light Crossbow",
        "Dart",
        "Shortbow",
        "Sling",
    ],
    "martial_weapon": [
        "Battleaxe",
        "Flail",
        "Glaive",
        "Greataxe",
        "Greatsword",
        "Halberd",
        "Lance",
        "Longsword",
        "Maul",
        "Morningstar",
        "Pike",
        "Rapier",
        "Scimitar",
        "Shortsword",
        "Trident",
        "War Pick",
        "Warhammer",
        "Whip",
        "Blowgun",
        "Hand Crossbow",
        "Heavy Crossbow",
        "Longbow",
        "Net",
    ],
    "light_armor": [
        "Padded Armor",
        "Leather Armor",
        "Studded Leather Armor",
    ],
    "medium_armor": [
        "Hide Armor",
        "Chain Shirt",
        "Scale Mail",
        "Breastplate",
        "Half Plate Armor",
    ],
    "heavy_armor": [
        "Ring Mail",
        "Chain Mail",
        "Splint Armor",
        "Plate Armor",
    ],
    "shield": [
        "Shield",
    ],
    "adventuring_gear": [
        "Abacus",
        "Acid",
        "Alchemist's Fire",
        "Backpack",
        "Ball Bearings",
        "Barrel",
        "Basket",
        "Bedroll",
        "Bell",
        "Blanket",
        "Block and Tackle",
        "Book",
        "Bottle, Glass",
        "Bucket",
        "Caltrops",
        "Candle",
        "Case, Crossbow Bolt",
        "Case, Map or Scroll",
        "Chain",
        "Chalk",
        "Chest",
        "Climber's Kit",
        "Clothes, Common",
        "Clothes, Costume",
        "Clothes, Fine",
        "Clothes, Traveler's",
        "Component Pouch",
        "Crowbar",
        "Fishing Tackle",
        "Flask or Tankard",
        "Grappling Hook",
        "Hammer",
        "Hammer, Sledge",
        "Healer's Kit",
        "Holy Symbol",
        "Holy Water",
        "Hourglass",
        "Hunting Trap",
        "Ink",
        "Ink Pen",
        "Jug or Pitcher",
        "Ladder",
        "Lamp",
        "Lantern, Bullseye",
        "Lantern, Hooded",
        "Lock",
        "Magnifying Glass",
        "Manacles",
        "Mess Kit",
        "Mirror, Steel",
        "Oil",
        "Paper",
        "Parchment",
        "Perfume",
        "Pick, Miner's",
        "Piton",
        "Poison, Basic",
        "Pole",
        "Pot, Iron",
        "Potion of Healing",
        "Pouch",
        "Quiver",
        "Ram, Portable",
        "Rations",
        "Robes",
        "Rope, Hempen",
        "Rope, Silk",
        "Sack",
        "Scale, Merchant's",
        "Sealing Wax",
        "Shovel",
        "Signal Whistle",
        "Signet Ring",
        "Soap",
        "Spellbook",
        "Spikes, Iron",
        "Spyglass",
        "Tent, Two-Person",
        "Tinderbox",
        "Torch",
        "Vial",
        "Waterskin",
        "Whetstone",
    ],
    "tool": [
        "Alchemist's Supplies",
        "Brewer's Supplies",
        "Calligrapher's Supplies",
        "Carpenter's Tools",
        "Cartographer's Tools",
        "Cobbler's Tools",
        "Cook's Utensils",
        "Disguise Kit",
        "Forgery Kit",
        "Glassblower's Tools",
        "Herbalism Kit",
        "Jeweler's Tools",
        "Leatherworker's Tools",
        "Mason's Tools",
        "Navigator's Tools",
        "Painter's Supplies",
        "Poisoner's Kit",
        "Potter's Tools",
        "Smith's Tools",
        "Thieves' Tools",
        "Tinker's Tools",
        "Weaver's Tools",
        "Woodcarver's Tools",
        "Dice Set",
        "Dragonchess Set",
        "Playing Card Set",
        "Three-Dragon Ante Set",
        "Bagpipes",
        "Drum",
        "Dulcimer",
        "Flute",
        "Horn",
        "Lute",
        "Lyre",
        "Pan Flute",
        "Shawm",
        "Viol",
    ],
    "mount_vehicle": [
        "Camel",
        "Donkey or Mule",
        "Elephant",
        "Horse, Draft",
        "Horse, Riding",
        "Mastiff",
        "Pony",
        "Warhorse",
        "Carriage",
        "Cart",
        "Chariot",
        "Galley",
        "Keelboat",
        "Longship",
        "Rowboat",
        "Sailing Ship",
        "Warship",
    ],
    "wondrous_magic": [
        "Adamantine Armor",
        "Ammunition, +1",
        "Ammunition, +2",
        "Ammunition, +3",
        "Amulet of Health",
        "Animated Shield",
        "Apparatus of the Crab",
        "Armor, +1",
        "Armor, +2",
        "Armor, +3",
        "Armor of Invulnerability",
        "Armor of Resistance",
        "Armor of Vulnerability",
        "Arrow-Catching Shield",
        "Bag of Beans",
        "Bag of Devouring",
        "Bag of Holding",
        "Bag of Tricks",
        "Bead of Force",
        "Belt of Dwarvenkind",
        "Belt of Giant Strength, Hill",
        "Belt of Giant Strength, Stone",
        "Belt of Giant Strength, Frost",
        "Belt of Giant Strength, Fire",
        "Belt of Giant Strength, Cloud",
        "Belt of Giant Strength, Storm",
        "Boots of Elvenkind",
        "Boots of Levitation",
        "Boots of Speed",
        "Boots of Striding and Springing",
        "Boots of the Winterlands",
        "Bracers of Archery",
        "Bracers of Defense",
        "Brazier of Commanding Fire Elementals",
        "Brooch of Shielding",
        "Broom of Flying",
        "Candle of Invocation",
        "Cape of the Mountebank",
        "Carpet of Flying",
        "Censer of Controlling Air Elementals",
        "Chime of Opening",
        "Circlet of Blasting",
        "Cloak of Arachnida",
        "Cloak of Displacement",
        "Cloak of Elvenkind",
        "Cloak of Protection",
        "Cloak of the Bat",
        "Cloak of the Manta Ray",
        "Crystal Ball",
        "Cube of Force",
        "Cubic Gate",
        "Dagger of Venom",
        "Deck of Many Things",
        "Decanter of Endless Water",
        "Demon Armor",
        "Dimensional Shackles",
        "Dragon Scale Mail",
        "Dragon Slayer",
        "Dust of Disappearance",
        "Dust of Dryness",
        "Dust of Sneezing and Choking",
        "Efficient Quiver",
        "Efreeti Bottle",
        "Elemental Gem",
        "Elixir of Health",
        "Elven Chain",
        "Eversmoking Bottle",
        "Eyes of Charming",
        "Eyes of Minute Seeing",
        "Eyes of the Eagle",
        "Feather Token",
        "Figurine of Wondrous Power",
        "Flame Tongue",
        "Folding Boat",
        "Frost Brand",
        "Gauntlets of Ogre Power",
        "Gem of Brightness",
        "Gem of Seeing",
        "Giant Slayer",
        "Glamoured Studded Leather",
        "Gloves of Missile Snaring",
        "Gloves of Swimming and Climbing",
        "Gloves of Thievery",
        "Goggles of Night",
        "Hammer of Thunderbolts",
        "Handy Haversack",
        "Hat of Disguise",
        "Headband of Intellect",
        "Helm of Brilliance",
        "Helm of Comprehending Languages",
        "Helm of Telepathy",
        "Helm of Teleportation",
        "Holy Avenger",
        "Horn of Blasting",
        "Horn of Valhalla",
        "Horseshoes of Speed",
        "Horseshoes of a Zephyr",
        "Immovable Rod",
        "Instant Fortress",
        "Ioun Stone",
        "Iron Bands of Binding",
        "Iron Flask",
        "Javelin of Lightning",
        "Lantern of Revealing",
        "Luck Blade",
        "Mace of Smiting",
        "Mace of Terror",
        "Mantle of Spell Resistance",
        "Manual of Bodily Health",
        "Manual of Gainful Exercise",
        "Manual of Golems",
        "Manual of Quickness of Action",
        "Marvelous Pigments",
        "Medallion of Thoughts",
        "Mirror of Life Trapping",
        "Mithral Armor",
        "Necklace of Adaptation",
        "Necklace of Fireballs",
        "Necklace of Prayer Beads",
        "Nine Lives Stealer",
        "Oathbow",
        "Oil of Etherealness",
        "Oil of Sharpness",
        "Oil of Slipperiness",
        "Periapt of Health",
        "Periapt of Proof Against Poison",
        "Periapt of Wound Closure",
        "Philter of Love",
        "Pipes of Haunting",
        "Pipes of the Sewers",
        "Portable Hole",
        "Potion of Animal Friendship",
        "Potion of Clairvoyance",
        "Potion of Climbing",
        "Potion of Diminution",
        "Potion of Flying",
        "Potion of Gaseous Form",
        "Potion of Giant Strength, Hill",
        "Potion of Growth",
        "Potion of Heroism",
        "Potion of Invisibility",
        "Potion of Mind Reading",
        "Potion of Poison",
        "Potion of Resistance",
        "Potion of Speed",
        "Potion of Water Breathing",
        "Quarterstaff of the Acrobat",
        "Ring of Animal Influence",
        "Ring of Djinni Summoning",
        "Ring of Elemental Command",
        "Ring of Evasion",
        "Ring of Feather Falling",
        "Ring of Free Action",
        "Ring of Invisibility",
        "Ring of Jumping",
        "Ring of Mind Shielding",
        "Ring of Protection",
        "Ring of Regeneration",
        "Ring of Resistance",
        "Ring of Shooting Stars",
        "Ring of Spell Storing",
        "Ring of Spell Turning",
        "Ring of Swimming",
        "Ring of Telekinesis",
        "Ring of the Ram",
        "Ring of Three Wishes",
        "Ring of Warmth",
        "Ring of Water Walking",
        "Ring of X-ray Vision",
        "Robe of Eyes",
        "Robe of Scintillating Colors",
        "Robe of Stars",
        "Robe of the Archmagi",
        "Robe of Useful Items",
        "Rod of Absorption",
        "Rod of Alertness",
        "Rod of Lordly Might",
        "Rod of Rulership",
        "Rod of Security",
        "Rope of Climbing",
        "Rope of Entanglement",
        "Scarab of Protection",
        "Shield, +1",
        "Shield, +2",
        "Shield, +3",
        "Shield of Missile Attraction",
        "Slippers of Spider Climbing",
        "Sovereign Glue",
        "Spell Scroll",
        "Spellguard Shield",
        "Sphere of Annihilation",
        "Staff of Charming",
        "Staff of Fire",
        "Staff of Frost",
        "Staff of Healing",
        "Staff of Power",
        "Staff of Striking",
        "Staff of Swarming Insects",
        "Staff of the Magi",
        "Staff of the Python",
        "Staff of the Woodlands",
        "Staff of Thunder and Lightning",
        "Staff of Withering",
        "Stone of Controlling Earth Elementals",
        "Stone of Good Luck",
        "Sun Blade",
        "Sword of Life Stealing",
        "Sword of Sharpness",
        "Sword of Wounding",
        "Talisman of Pure Good",
        "Talisman of the Sphere",
        "Talisman of Ultimate Evil",
        "Tome of Clear Thought",
        "Tome of Leadership and Influence",
        "Tome of Understanding",
        "Trident of Fish Command",
        "Universal Solvent",
        "Vicious Weapon",
        "Vorpal Sword",
        "Wand of Binding",
        "Wand of Enemy Detection",
        "Wand of Fear",
        "Wand of Fireballs",
        "Wand of Lightning Bolts",
        "Wand of Magic Detection",
        "Wand of Magic Missiles",
        "Wand of Paralysis",
        "Wand of Polymorph",
        "Wand of Secrets",
        "Wand of the War Mage, +1",
        "Wand of the War Mage, +2",
        "Wand of the War Mage, +3",
        "Wand of Web",
        "Wand of Wonder",
        "Weapon, +1",
        "Weapon, +2",
        "Weapon, +3",
        "Well of Many Worlds",
        "Wind Fan",
        "Winged Boots",
        "Wings of Flying",
    ],
}

SRD_ITEM_COUNT = sum(len(v) for v in SRD_ITEMS_BY_CATEGORY.values())
