"""SRD 5.1 CC-BY-4.0 spell name manifest for seed audit.

Reconcile against official SRD 5.1 Creative Commons source.
"""

SRD_SPELLS_BY_LEVEL = {
    0: [
        'Acid Splash',
        'Blade Ward',
        'Chill Touch',
        'Create Bonfire',
        'Dancing Lights',
        'Druidcraft',
        'Eldritch Blast',
        'Fire Bolt',
        'Frostbite',
        'Guidance',
        'Light',
        'Mage Hand',
        'Mending',
        'Message',
        'Minor Illusion',
        'Poison Spray',
        'Prestidigitation',
        'Produce Flame',
        'Ray of Frost',
        'Resistance',
        'Sacred Flame',
        'Shillelagh',
        'Shocking Grasp',
        'Spare the Dying',
        'Thaumaturgy',
        'Toll the Dead',
        'True Strike',
        'Vicious Mockery',
        'Word of Radiance',
    ],
    1: [
        'Alarm',
        'Animal Friendship',
        'Arms of Hadar',
        'Bane',
        'Bless',
        'Burning Hands',
        'Charm Person',
        'Color Spray',
        'Command',
        'Compelled Duel',
        'Comprehend Languages',
        'Create or Destroy Water',
        'Cure Wounds',
        'Detect Evil and Good',
        'Detect Magic',
        'Detect Poison and Disease',
        'Disguise Self',
        'Divine Favor',
        'Ensnaring Strike',
        'Entangle',
        'Expeditious Retreat',
        'Faerie Fire',
        'False Life',
        'Feather Fall',
        'Find Familiar',
        'Floating Disk',
        'Fog Cloud',
        'Goodberry',
        'Grease',
        'Guiding Bolt',
        'Healing Word',
        'Hellish Rebuke',
        'Heroism',
        'Hideous Laughter',
        "Hunter's Mark",
        'Identify',
        'Illusory Script',
        'Inflict Wounds',
        'Jump',
        'Longstrider',
        'Mage Armor',
        'Magic Missile',
        'Protection from Evil and Good',
        'Purify Food and Drink',
        'Sanctuary',
        'Searing Smite',
        'Shield',
        'Shield of Faith',
        'Silent Image',
        'Sleep',
        'Speak with Animals',
        'Thunderous Smite',
        'Thunderwave',
        'Unseen Servant',
        'Wrathful Smite',
    ],
    2: [
        'Acid Arrow',
        'Aid',
        'Alter Self',
        'Animal Messenger',
        'Arcane Lock',
        "Arcanist's Magic Aura",
        'Augury',
        'Barkskin',
        'Beast Sense',
        'Blindness/Deafness',
        'Blur',
        'Branding Smite',
        'Calm Emotions',
        'Continual Flame',
        'Darkness',
        'Darkvision',
        'Detect Thoughts',
        'Enhance Ability',
        'Enlarge/Reduce',
        'Enthrall',
        'Find Steed',
        'Find Traps',
        'Flame Blade',
        'Flaming Sphere',
        'Gentle Repose',
        'Gust of Wind',
        'Heat Metal',
        'Hold Person',
        'Invisibility',
        'Knock',
        'Lesser Restoration',
        'Levitate',
        'Locate Animals or Plants',
        'Locate Object',
        'Magic Mouth',
        'Magic Weapon',
        'Mirror Image',
        'Misty Step',
        'Moonbeam',
        'Pass without Trace',
        'Phantasmal Force',
        'Protection from Poison',
        'Ray of Enfeeblement',
        'Rope Trick',
        'Scorching Ray',
        'See Invisibility',
        'Shatter',
        'Silence',
        'Spider Climb',
        'Spike Growth',
        'Spiritual Weapon',
        'Suggestion',
        'Warding Bond',
        'Web',
        'Zone of Truth',
    ],
    3: [
        'Animate Dead',
        'Beacon of Hope',
        'Bestow Curse',
        'Blink',
        'Call Lightning',
        'Clairvoyance',
        'Conjure Animals',
        'Conjure Barrage',
        'Counterspell',
        'Create Food and Water',
        'Daylight',
        'Dispel Magic',
        'Fear',
        'Feign Death',
        'Fireball',
        'Fly',
        'Gaseous Form',
        'Glyph of Warding',
        'Haste',
        'Hypnotic Pattern',
        'Lightning Arrow',
        'Lightning Bolt',
        'Magic Circle',
        'Major Image',
        'Mass Healing Word',
        'Meld into Stone',
        'Nondetection',
        'Phantom Steed',
        'Plant Growth',
        'Protection from Energy',
        'Remove Curse',
        'Revivify',
        'Sleet Storm',
        'Slow',
        'Speak with Dead',
        'Speak with Plants',
        'Spirit Guardians',
        'Stinking Cloud',
        'Tongues',
        'Vampiric Touch',
        'Water Breathing',
        'Water Walk',
        'Wind Wall',
    ],
    4: [
        'Arcane Eye',
        'Banishment',
        'Black Tentacles',
        'Blight',
        'Compulsion',
        'Confusion',
        'Conjure Minor Elementals',
        'Conjure Woodland Beings',
        'Control Water',
        'Death Ward',
        'Dimension Door',
        'Divination',
        'Dominate Beast',
        'Fabricate',
        'Fire Shield',
        'Freedom of Movement',
        'Giant Insect',
        'Hallucinatory Terrain',
        'Ice Storm',
        'Locate Creature',
        'Phantasmal Killer',
        'Polymorph',
        'Private Sanctum',
        'Resilient Sphere',
        'Secret Chest',
        'Stone Shape',
        'Stoneskin',
        'Wall of Fire',
    ],
    5: [
        'Animate Objects',
        'Antilife Shell',
        'Arcane Hand',
        'Awaken',
        'Banishing Smite',
        'Circle of Power',
        'Cloudkill',
        'Commune',
        'Commune with Nature',
        'Cone of Cold',
        'Conjure Elemental',
        'Contact Other Plane',
        'Contagion',
        'Creation',
        'Destructive Wave',
        'Dispel Evil and Good',
        'Dominate Person',
        'Dream',
        'Flame Strike',
        'Geas',
        'Greater Restoration',
        'Hold Monster',
        'Insect Plague',
        'Legend Lore',
        'Mass Cure Wounds',
        'Mislead',
        'Modify Memory',
        'Passwall',
        'Planar Binding',
        'Raise Dead',
        'Reincarnate',
        'Scrying',
        'Seeming',
        'Telekinesis',
        'Teleportation Circle',
        'Tree Stride',
        'Wall of Force',
        'Wall of Stone',
    ],
    6: [
        'Blade Barrier',
        'Chain Lightning',
        'Circle of Death',
        'Conjure Fey',
        'Contingency',
        'Create Undead',
        'Disintegrate',
        'Eyebite',
        'Find the Path',
        'Flesh to Stone',
        'Forbiddance',
        'Freezing Sphere',
        'Harm',
        'Heal',
        "Heroes' Feast",
        'Instant Summons',
        'Irresistible Dance',
        'Magic Jar',
        'Mass Suggestion',
        'Move Earth',
        'Planar Ally',
        'Programmed Illusion',
        'Sunbeam',
        'Transport via Plants',
        'True Seeing',
        'Wall of Ice',
        'Word of Recall',
    ],
    7: [
        'Arcane Sword',
        'Conjure Celestial',
        'Delayed Blast Fireball',
        'Divine Word',
        'Etherealness',
        'Finger of Death',
        'Fire Storm',
        'Magnificent Mansion',
        'Mirage Arcane',
        'Plane Shift',
        'Prismatic Spray',
        'Project Image',
        'Regenerate',
        'Resurrection',
        'Reverse Gravity',
        'Teleport',
    ],
    8: [
        'Animal Shapes',
        'Antimagic Field',
        'Antipathy/Sympathy',
        'Clone',
        'Control Weather',
        'Earthquake',
        'Feeblemind',
        'Holy Aura',
        'Incendiary Cloud',
        'Mind Blank',
        'Power Word Stun',
        'Sunburst',
        'Tsunami',
    ],
    9: [
        'Astral Projection',
        'Foresight',
        'Gate',
        'Imprisonment',
        'Mass Heal',
        'Meteor Swarm',
        'Power Word Kill',
        'Prismatic Wall',
        'Shapechange',
        'Storm of Vengeance',
        'Time Stop',
        'True Polymorph',
        'True Resurrection',
        'Weird',
        'Wish',
    ],
}

SRD_SPELL_COUNT = sum(len(v) for v in SRD_SPELLS_BY_LEVEL.values())
