"""tick system

Revision ID: 05567566c73b
Revises: b95ff87725cd
Create Date: 2025-03-29 15:52:34.873965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05567566c73b'
down_revision = 'b95ff87725cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sim_rules',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('function_type', sa.String(length=50), nullable=False),
    sa.Column('condition_json', sa.JSON(), nullable=False),
    sa.Column('gm_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gm_profile_id'], ['gm_profile.id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('simulation_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('tick_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('gm_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gm_profile_id'], ['gm_profile.id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('simulation_state',
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('current_tick', sa.Integer(), nullable=False),
    sa.Column('speed', sa.String(length=10), nullable=False),
    sa.Column('last_tick_time', sa.DateTime(), nullable=False),
    sa.Column('gm_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gm_profile_id'], ['gm_profile.id'], ),
    sa.PrimaryKeyConstraint('state_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_state')
    op.drop_table('simulation_logs')
    op.drop_table('sim_rules')
    # ### end Alembic commands ###
