"""Add detailed fields to items table

Revision ID: 1057540e69ef
Revises: a026591fc989
Create Date: 2025-01-28 12:50:59.991081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1057540e69ef'
down_revision = 'a026591fc989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('range', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('damage', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('rate_of_fire', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('min_str', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('base_price',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('base_price',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('notes')
        batch_op.drop_column('min_str')
        batch_op.drop_column('rate_of_fire')
        batch_op.drop_column('damage')
        batch_op.drop_column('range')

    # ### end Alembic commands ###
