"""initial migration

Revision ID: 1b9d137646b7
Revises: 
Create Date: 2025-03-24 20:29:51.426016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9d137646b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gm_profile_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'gm_profile', ['gm_profile_id'], ['id'])

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gm_profile_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'gm_profile', ['gm_profile_id'], ['id'])

    with op.batch_alter_table('modifier_targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gm_profile_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'gm_profile', ['gm_profile_id'], ['id'])

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gm_profile_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('player_gm_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'gm_profile', ['gm_profile_id'], ['id'])
        batch_op.drop_column('gm_id')

    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gm_profile_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'gm_profile', ['gm_profile_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gm_profile_id')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gm_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('player_gm_id_fkey', 'user', ['gm_id'], ['id'])
        batch_op.drop_column('gm_profile_id')

    with op.batch_alter_table('modifier_targets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gm_profile_id')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gm_profile_id')

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gm_profile_id')

    # ### end Alembic commands ###
