"""Fix cascading delete for cities and shops

Revision ID: 462fa9dbd89a
Revises: 68ee88b9176f
Create Date: 2025-02-26 14:21:14.320506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462fa9dbd89a'
down_revision = '68ee88b9176f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_inventory', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_inventory', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
