"""Add demand mod sytstem

Revision ID: 4a0e4e4bb229
Revises: bcdb68727bc1
Create Date: 2025-03-03 14:46:54.196166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0e4e4bb229'
down_revision = 'bcdb68727bc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand_modifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.Enum('global', 'regional', 'city', 'shop', 'item', name='modifier_scope'), nullable=False),
    sa.Column('effect_value', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modifier_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modifier_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('region', 'city', 'shop', 'item', name='target_type'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modifier_id'], ['demand_modifiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modifier_targets')
    op.drop_table('demand_modifiers')
    # ### end Alembic commands ###
