"""Re-add city_id and shop_id columns

Revision ID: 5ac8e5c08ac4
Revises: 735b50001d54
Create Date: 2025-01-28 13:31:07.591123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac8e5c08ac4'
down_revision = '735b50001d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_column('city_id')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('shop_id')

    # ### end Alembic commands ###
