"""Recreated migrations folder and many-to-many relationship

Revision ID: 6425cc4b2d6a
Revises: e3e94c21ab57
Create Date: 2025-01-28 20:01:44.167206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6425cc4b2d6a'
down_revision = 'e3e94c21ab57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_cities',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.shop_id'], ),
    sa.PrimaryKeyConstraint('shop_id', 'city_id')
    )
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_column('city_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.INTEGER(), nullable=True))

    op.drop_table('shop_cities')
    # ### end Alembic commands ###
