"""Allow NULL values for shop_id and item_id in shop_inventory

Revision ID: 68ee88b9176f
Revises: 8e8a6137895f
Create Date: 2025-02-26 13:49:25.374046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ee88b9176f'
down_revision = '8e8a6137895f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_inventory', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_inventory', schema=None) as batch_op:
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
