"""Fixed many-to-many shop-city relationship

Revision ID: 6a72a1c267f3
Revises: 6425cc4b2d6a
Create Date: 2025-01-28 20:20:54.242405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a72a1c267f3'
down_revision = '6425cc4b2d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('shop_id')

    with op.batch_alter_table('shop_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dynamic_price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_inventory', schema=None) as batch_op:
        batch_op.drop_column('dynamic_price')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
