"""Remove foreign key constraints from Shop and Item

Revision ID: 735b50001d54
Revises: 1057540e69ef
Create Date: 2025-01-28 13:14:48.817424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735b50001d54'
down_revision = '1057540e69ef'
branch_labels = None
depends_on = None


def upgrade():
    # Remove the shop_id column from the items table
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_column("shop_id")

    # Remove the city_id column from the shops table
    with op.batch_alter_table("shops", schema=None) as batch_op:
        batch_op.drop_column("city_id")


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'cities', ['city_id'], ['city_id'])
        batch_op.alter_column('city_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'shops', ['shop_id'], ['shop_id'])

    # ### end Alembic commands ###
