"""name column

Revision ID: 82a1856370df
Revises: 4635643ccd04
Create Date: 2025-01-28 09:33:31.912853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a1856370df'
down_revision = '4635643ccd04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
