"""Aloow Null values in shop_inventory

Revision ID: 8e8a6137895f
Revises: 
Create Date: 2025-02-26 13:36:40.806969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8a6137895f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_constraint('cities_name_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_cities_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_cities_region'), ['region'], unique=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('items_name_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_items_name'), ['name'], unique=False)

    with op.batch_alter_table('shop_inventory', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_constraint('shops_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.create_unique_constraint('shops_name_key', ['name'])

    with op.batch_alter_table('shop_inventory', schema=None) as batch_op:
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_name'))
        batch_op.create_unique_constraint('items_name_key', ['name'])

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cities_region'))
        batch_op.drop_index(batch_op.f('ix_cities_name'))
        batch_op.create_unique_constraint('cities_name_key', ['name'])

    # ### end Alembic commands ###
