"""Added User model

Revision ID: bcdb68727bc1
Revises: de917469019f
Create Date: 2025-03-03 10:27:15.689117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcdb68727bc1'
down_revision = 'de917469019f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('users')
    with op.batch_alter_table('shop_inventory', schema=None) as batch_op:
        batch_op.drop_constraint('shop_inventory_item_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('shop_inventory_shop_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'shops', ['shop_id'], ['shop_id'])
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['item_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('shop_inventory_shop_id_fkey', 'shops', ['shop_id'], ['shop_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('shop_inventory_item_id_fkey', 'items', ['item_id'], ['item_id'], ondelete='CASCADE')

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'Player'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("role::text = ANY (ARRAY['GM'::character varying, 'Player'::character varying]::text[])", name='role_check'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
