"""Remove cascade delete from shop_cities

Revision ID: de917469019f
Revises: f3ab8066ece8
Create Date: 2025-02-26 14:30:30.684009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de917469019f'
down_revision = 'f3ab8066ece8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_cities', schema=None) as batch_op:
        batch_op.drop_constraint('shop_cities_shop_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'shops', ['shop_id'], ['shop_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_cities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('shop_cities_shop_id_fkey', 'shops', ['shop_id'], ['shop_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
