"""Fix Shop and ShopInventory relationships and enable cascading deletes

Revision ID: e3e94c21ab57
Revises: 5ac8e5c08ac4
Create Date: 2025-01-28 17:34:54.028367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e94c21ab57'
down_revision = '5ac8e5c08ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_inventory',
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.shop_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_inventory')
    # ### end Alembic commands ###
