"""Fix cascade delete for shop_cities

Revision ID: f3ab8066ece8
Revises: 462fa9dbd89a
Create Date: 2025-02-26 14:26:43.012541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3ab8066ece8'
down_revision = '462fa9dbd89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_cities', schema=None) as batch_op:
        batch_op.drop_constraint('shop_cities_shop_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'shops', ['shop_id'], ['shop_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_cities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('shop_cities_shop_id_fkey', 'shops', ['shop_id'], ['shop_id'], ondelete='SET NULL')

    # ### end Alembic commands ###
