"""SRD 5.1 CC-BY-4.0 monster name manifest for seed audit.

Reconcile against official SRD 5.1 Creative Commons source.
"""

SRD_MONSTERS_BY_CR = {
    '0': [
        'Homunculus',
        'Lemure',
        'Shrieker',
    ],
    '0.125': [
        'Kobold',
        'Merfolk',
        'Stirge',
    ],
    '0.25': [
        'Dretch',
        'Elf, Drow',
        'Flying Sword',
        'Goblin',
        'Grimlock',
        'Pseudodragon',
        'Skeleton',
        'Sprite',
        'Steam Mephit',
        'Violet Fungus',
        'Zombie',
    ],
    '0.5': [
        'Cockatrice',
        'Darkmantle',
        'Dust Mephit',
        'Gnoll',
        'Gnome, Deep (Svirfneblin)',
        'Gray Ooze',
        'Hobgoblin',
        'Ice Mephit',
        'Lizardfolk',
        'Magma Mephit',
        'Magmin',
        'Orc',
        'Rust Monster',
        'Sahuagin',
        'Satyr',
        'Shadow',
        'Warhorse Skeleton',
    ],
    '1': [
        'Animated Armor',
        'Brass Dragon Wyrmling',
        'Bugbear',
        'Copper Dragon Wyrmling',
        'Dryad',
        'Duergar',
        'Ghoul',
        'Harpy',
        'Hippogriff',
        'Imp',
        'Quasit',
        'Specter',
    ],
    '2': [
        'Ankheg',
        'Azer',
        'Black Dragon Wyrmling',
        'Bronze Dragon Wyrmling',
        'Centaur',
        'Ettercap',
        'Gargoyle',
        'Gelatinous Cube',
        'Ghast',
        'Gibbering Mouther',
        'Green Dragon Wyrmling',
        'Grick',
        'Griffon',
        'Merrow',
        'Mimic',
        'Minotaur Skeleton',
        'Ochre Jelly',
        'Ogre',
        'Ogre Zombie',
        'Pegasus',
        'Plesiosaurus',
        'Rug of Smothering',
        'Sea Hag',
        'Silver Dragon Wyrmling',
        'Wererat',
        'White Dragon Wyrmling',
        'Will--o’--Wisp',
    ],
    '3': [
        'Basilisk',
        'Bearded Devil',
        'Blue Dragon Wyrmling',
        'Doppelganger',
        'Gold Dragon Wyrmling',
        'Green Hag',
        'Hell Hound',
        'Manticore',
        'Minotaur',
        'Mummy',
        'Nightmare',
        'Owlbear',
        'Werewolf',
        'Wight',
    ],
    '4': [
        'Black Pudding',
        'Chuul',
        'Couatl',
        'Ettin',
        'Ghost',
        'Lamia',
        'Red Dragon Wyrmling',
        'Succubus/Incubus',
        'Wereboar',
        'Weretiger',
    ],
    '5': [
        'Air Elemental',
        'Barbed Devil',
        'Bulette',
        'Earth Elemental',
        'Fire Elemental',
        'Flesh Golem',
        'Gorgon',
        'Half--Red Dragon Veteran',
        'Hill Giant',
        'Night Hag',
        'Otyugh',
        'Roper',
        'Salamander',
        'Shambling Mound',
        'Triceratops',
        'Troll',
        'Unicorn',
        'Vampire Spawn',
        'Water Elemental',
        'Werebear',
        'Wraith',
        'Xorn',
    ],
    '6': [
        'Chimera',
        'Drider',
        'Invisible Stalker',
        'Medusa',
        'Vrock',
        'Wyvern',
        'Young Brass Dragon',
        'Young White Dragon',
    ],
    '7': [
        'Oni',
        'Shield Guardian',
        'Stone Giant',
        'Young Black Dragon',
        'Young Copper Dragon',
    ],
    '8': [
        'Chain Devil',
        'Cloaker',
        'Frost Giant',
        'Hezrou',
        'Hydra',
        'Spirit Naga',
        'Tyrannosaurus Rex',
        'Young Bronze Dragon',
        'Young Green Dragon',
    ],
    '9': [
        'Bone Devil',
        'Clay Golem',
        'Cloud Giant',
        'Fire Giant',
        'Glabrezu',
        'Treant',
        'Young Blue Dragon',
        'Young Silver Dragon',
    ],
    '10': [
        'Aboleth',
        'Deva',
        'Guardian Naga',
        'Stone Golem',
        'Young Gold Dragon',
        'Young Red Dragon',
    ],
    '11': [
        'Behir',
        'Djinni',
        'Efreeti',
        'Gynosphinx',
        'Horned Devil',
        'Remorhaz',
        'Roc',
    ],
    '12': [
        'Erinyes',
    ],
    '13': [
        'Adult Brass Dragon',
        'Adult White Dragon',
        'Nalfeshnee',
        'Rakshasa',
        'Storm Giant',
        'Vampire',
    ],
    '14': [
        'Adult Black Dragon',
        'Adult Copper Dragon',
        'Ice Devil',
    ],
    '15': [
        'Adult Bronze Dragon',
        'Adult Green Dragon',
        'Mummy Lord',
        'Purple Worm',
    ],
    '16': [
        'Adult Blue Dragon',
        'Adult Silver Dragon',
        'Iron Golem',
        'Marilith',
        'Planetar',
    ],
    '17': [
        'Adult Gold Dragon',
        'Adult Red Dragon',
        'Androsphinx',
        'Dragon Turtle',
    ],
    '19': [
        'Balor',
    ],
    '20': [
        'Ancient Brass Dragon',
        'Ancient White Dragon',
        'Pit Fiend',
    ],
    '21': [
        'Ancient Black Dragon',
        'Ancient Copper Dragon',
        'Lich',
        'Solar',
    ],
    '22': [
        'Ancient Bronze Dragon',
        'Ancient Green Dragon',
    ],
    '23': [
        'Ancient Silver Dragon',
        'Blue Dragon Ancient Blue Dragon',
        'Kraken',
    ],
    '24': [
        'Ancient Gold Dragon',
        'Ancient Red Dragon',
    ],
}

SRD_MONSTER_COUNT = 200
